name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: clone repository and set committer identity
      - name: Clone repo
        run: |
          git clone https://github.com/stevenliuyi/ChatGPT-Next-Web.git
          cd ChatGPT-Next-Web
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      # Step 2: merge changes from upstream repo
      - name: Merge upstream
        run: |
          cd ChatGPT-Next-Web
          git remote add upstream https://github.com/Yidadaa/ChatGPT-Next-Web.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git commit -m "Merged upstream"
          git push origin HEAD
